FROM golang AS golang-builder

FROM l.gcr.io/google/bazel

COPY --from=golang-builder /usr/local/go /usr/local/go
RUN ln -s /usr/local/go/bin/go /bin/go

ENV DAPPER_SOURCE /workspace
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_OUTPUT bin

WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["make", "build"]
