#!/usr/bin/env bash

gen(){
	bkyml steps
	bkyml command --command "make test-build" --label 'test-build'
	bkyml command --command "make build-linux" --artifact-paths 'bin/*/*/*' --label 'build-linux'
}

main(){
  gen | grep .
}

main
