/*
Copyright 2014 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package apis

import (
	"net/http"

	"github.com/emicklei/go-restful/v3"

	"k8s.io/apiserver/pkg/endpoints/handlers/responsewriters"
)

// Version provides a webservice with version information.
type APIS struct{}

type Version struct {
	GroupVersion string `json:"groupVersion"`
	Version      string `json:"version"`
}

type PreferredVersion struct {
	GroupVersion string `json:"groupVersion"`
	Version      string `json:"version"`
}

type Group struct {
	Name             string           `json:"name"`
	Versions         []Version        `json:"versions"`
	PreferredVersion PreferredVersion `json:"preferredVersion"`
}

// curl http://localhost:8002/apis | jq . | https://mholt.github.io/json-to-go/
type AutoGenerated struct {
	Kind       string  `json:"kind"`
	APIVersion string  `json:"apiVersion"`
	Groups     []Group `json:"groups"`
}

// Install registers the APIServer's `/version` handler.
func (v APIS) Install(c *restful.Container) {

	// Set up a service to return the git code version.
	versionWS := new(restful.WebService)
	versionWS.Path("/apis")
	versionWS.Doc("git code version from which this is built")
	versionWS.Route(
		versionWS.GET("/").To(v.handleVersion).
			Doc("get the code version").
			Operation("getCodeVersion").
			Produces(restful.MIME_JSON).
			Consumes(restful.MIME_JSON).
			Writes(DUMP))
	/*
		versionWS.Path("/apis/node.k8s.io/v1")
		versionWS.Doc("git code version from which this is built")
		versionWS.Route(
			versionWS.GET("/").To(v.handleVersion).
				Doc("get the code version").
				Operation("getCodeVersion").
				Produces(restful.MIME_JSON).
				Consumes(restful.MIME_JSON).
				Writes(struct{}{}))
	*/

	c.Add(versionWS)
}

var DUMP = AutoGenerated{
	Kind:       "APIGroupList",
	APIVersion: "v1",
	Groups: []Group{
		Group{
			Name: "node.k8s.io",
			Versions: []Version{
				Version{
					Version:      "v1",
					GroupVersion: "node.k8s.io/v1",
				},
			},
			PreferredVersion: PreferredVersion{
				Version:      "v1",
				GroupVersion: "node.k8s.io/v1",
			},
		},
	},
}

// handleVersion writes the server's version information.
func (v APIS) handleVersion(req *restful.Request, resp *restful.Response) {
	responsewriters.WriteRawJSON(http.StatusOK, DUMP, resp.ResponseWriter)
}
