#!/usr/bin/env bash

. .env

# https://grafana.com/grafana/download
if ! [[ -f grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz ]]; then
  wget https://dl.grafana.com/oss/release/grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz
fi
tar -zxvf grafana-${GRAFANA_VERSION}.linux-amd64.tar.gz

# https://prometheus.io/download/
if ! [[ -f prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz ]]; then
  wget https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz
fi
tar -zxvf prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz

# https://prometheus.io/download/#alertmanager
if ! [[ -f alertmanager-${ALERTMANAGER_VERSION}.linux-amd64.tar.gz ]]; then
  wget https://github.com/prometheus/alertmanager/releases/download/v${ALERTMANAGER_VERSION}/alertmanager-${ALERTMANAGER_VERSION}.linux-amd64.tar.gz
fi
tar -zxvf alertmanager-${ALERTMANAGER_VERSION}.linux-amd64.tar.gz

# https://prometheus.io/download/#node_exporter
if ! [[ -f node_exporter-${NODE_EXPORTER_VERSION}.linux-amd64.tar.gz ]]; then
  wget https://github.com/prometheus/node_exporter/releases/download/v${NODE_EXPORTER_VERSION}/node_exporter-${NODE_EXPORTER_VERSION}.linux-amd64.tar.gz
fi
tar -zxvf node_exporter-${NODE_EXPORTER_VERSION}.linux-amd64.tar.gz
