#!/usr/bin/env bash

HUB="${1:-hub.k0s.io}"

assert_exists(){
  cmds="$@"
  quit=""
  for cmd in $cmds; do
    echo "assert exists: $cmd"
    command -v "$cmd" &>/dev/null || quit+="$cmd "
  done
  
  [[ -n "$quit" ]] && echo "command not found: $quit" && exit 1
}

init(){
  assert_exists curl jq docker-compose
  touch ${targets_file}
  mkdir -p data grafana prometheus
  chmod 777 ${targets_file} data grafana prometheus
}

main(){
  targets_file="prometheus_scrape_targets.json"
  cd $(dirname "$0")
  init
  ./update_scrape_targets "${HUB}" &
  docker-compose up
}

main "$@"
