#!/usr/bin/env bash

HUB="${1:-hub.k0s.io}"

get_hub(){
  printf '{"targets": ["%s"], "labels": {"job": "__hub__", "__metrics_path__": "/api/metrics"}}' "${HUB}"
}

jq_filter(){
  printf '.[]|{"targets": ["%s"], "labels": {"job": "\(.name)", "__metrics_path__": "/api/agent/\(.id)/metrics"}}' "${HUB}"
}

get_agents(){
  curl -s https://${HUB}/api/agents/list | jq -c "$(jq_filter)"
}

update_targets(){
  src=/tmp/${targets_file}
  dst=./${targets_file}
  (get_hub && get_agents) | jq -s . >$src;
  if ! diff ${src} ${dst} &>/dev/null; then
    cp -v ${src} ${dst}
    cat ${dst} | jq -c .[]
  fi
}

update_targets_loop(){
  while :; do update_targets; sleep 2; done
}

main(){
  targets_file="prometheus_scrape_targets.json"
  update_targets_loop
}

main "$@"
