#!/usr/bin/env bash

start(){
  cat <<EOF | grep -v '^[[:space:]]*#' | grep . | xpanes -te
  env "GF_PATHS_DATA=$PWD/grafana" ./grafana-6.6.1/bin/grafana-server -homepath=grafana-6.6.1 --config="$PWD/grafana.ini"

  ./update_scrape_targets

  prometheus --storage.tsdb.path=prometheus --config.file=prometheus.yml --web.listen-address=0.0.0.0:9090 --web.external-url=https://k0s.io/prometheus --web.route-prefix=/prometheus
EOF
}

main(){
  start
}

main "$@"
