#!/usr/bin/env bash

set -e

for distro in {alpine,ubuntu,debian,centos,fedora,gentoo,arch,latest}; do
  img=btwiuse/k0s:${distro}
  echo ====== building $img ========
  docker build -q --no-cache -f Dockerfile.${distro} . -t $img
  (docker push $img &>/dev/null && echo pushed $img) &
done

wait
