#!/usr/bin/env bash

for distro in {alpine,ubuntu,debian,centos,fedora,gentoo,arch}; do
  img=conntroll/agent:${distro}
  echo ====== building $img ========
  docker build --no-cache -f Dockerfile.agent.${distro} . -t img
  docker push $img
done

for bin in {conntroll,agent,hub,client}; do
  img=conntroll/${bin}
  echo ====== building conntroll/${bin} ======
  docker build --no-cache -f Dockerfile.${bin} . -t $img
  docker push $img
done
