FROM fedora

ADD https://conntroll.github.io/releases/latest/linux/amd64/conntroll /bin/conntroll
ADD agent.yaml /etc/conntroll/agent.yaml
RUN chmod +x /bin/conntroll
RUN ln -f /bin/conntroll /bin/hub
RUN ln -f /bin/conntroll /bin/agent
RUN ln -f /bin/conntroll /bin/client

ENTRYPOINT ["agent"]
