FROM ubuntu

RUN apt update && apt install -y curl
ADD https://conntroll.github.io/busybox /bin/busybox
ADD entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/bosybox

ENTRYPOINT ["/bin/entrypoint.sh"]
