#!/usr/bin/env bash

PREV=v0.1.18-alpha.3
NEXT=$(<VERSION)

cat .mods | while read a; do
  echo "s,$a $PREV$,$a $NEXT,g"
  echo "s,$a $PREV // indirect$,$a $NEXT // indirect,g"
done > /tmp/sed
find . -name go.mod | xargs -L1 sed -i -f /tmp/sed
sed -i -f /tmp/sed go.work
