#!/usr/bin/env bash

export BUSYBOX="${PWD}/.bin"

if ! [[ -d "${BUSYBOX}" ]]; then
  mkdir -p "${BUSYBOX}"
fi

curl -sL https://busybox.net/downloads/binaries/1.31.0-defconfig-multiarch-musl/busybox-x86_64 > ${BUSYBOX}/busybox
chmod +x ${BUSYBOX}/busybox
${BUSYBOX}/busybox --install ${BUSYBOX}

export PATH="${PATH}:${BUSYBOX}"
