#!/usr/bin/env bash

VERSION=$(cat VERSION)

ROOT_MOD=$(go mod edit -json | jq -r .Module.Path)

ROOT=$(pwd)

echo $ROOT

modpaths(){
  cd $ROOT
  go work edit --json | jq .Use[] -c | jq -r .DiskPath | while read a ; do realpath $a; done
}

modpaths2(){
  cd $ROOT
  go work edit --json | jq .Use[] -c | jq -r '"\(.ModPath) \(.DiskPath)/"' | while read a b; do echo $a $(realpath $b); done
}


mods(){
  go mod edit -json | jq -cr '.Require[]?|.Path' | grep $ROOT_MOD
}

modpaths | while read dir; do
  pushd $dir
  MODS="$(mods)"
  modpaths2 | while read mod path; do
    dst="${prefix}$(realpath --relative-to $PWD $path)/"
    [[ $dst == .* ]] && dst="./${dst}"
    go mod edit -dropreplace=${mod}
    grep -q "^${mod}$" <<<"$MODS" && {
      go mod edit -require=${mod}@${VERSION}
    }
  done
  # sleep 1
  popd
done
