#!/usr/bin/env bash

# slave1
curl -X POST https://cloud.docker.com/api/build/v1/source/20c53fe8-6029-4605-b5cf-c6377c3a7671/trigger/e248ef85-d16b-4ba8-ae2f-67799bd9d391/call/
# slave 2
curl -X POST https://cloud.docker.com/api/build/v1/source/8ca1f79e-abda-4c42-855e-272d8a993f89/trigger/8d3ab456-cdf8-4f8f-b270-1d7f0da5803d/call/

while :; do
  docker pull invctrl/client:latest
  # docker run --privileged -v /root:/root -v /var/run/docker.sock:/var/run/docker.sock -v /src:/src -w /root invctrl/client
  # docker run -dit -v /root:/root -v /home:/home -v /src:/src -v /var/run/docker.sock:/var/run/docker.sock --privileged --name dind --rm docker:dind /bin/sh
  docker run -dit -v /root:/root -v /home:/home -v /src:/src -v /var/run/docker.sock:/var/run/docker.sock --privileged --name dind --rm invctrl/client 
  # docker exec -i dind /bin/client
  echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDX5+yq0TQrW6lxsx0hcT+93A4K0QZ92UWM0BY0cc8ahyIey9/biN54at0xSSnu351ltJJdcp3O5XYs4qwCMiRBL+4YiNod0GF7hUb9yvQh6+SeiKy5y+0ChipUTXo3hK2wZ7plq6rI9JUu63E8TDWWG2Miy0dpn7YrCe2h27Jb7SZ9cc6df9JLXhXBcleHFrY0MDPGWfaMD2jnXGQFfyiFFyH/PlL3Ztu2BghozbZUlq7n4y8QpLcyko4n8OhtupIuQ4NHF4bKxwNrVdhLmG24IqLTTRIyUkHEJvwCENmP2kNy3NkNw+pdhJzG/e8DrG30HKat7flyFZp8TDEluVwB' | docker exec -i dind /bin/sh -c 'cat >>/home/ubuntu/.ssh/authorized_keys'
  sleep 1
done
