// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: asciiproto.proto

package asciiproto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*Frame_O
	//	*Frame_I
	//	*Frame_R
	Event isFrame_Event `protobuf_oneof:"Event"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asciiproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_asciiproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_asciiproto_proto_rawDescGZIP(), []int{0}
}

func (m *Frame) GetEvent() isFrame_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *Frame) GetO() []byte {
	if x, ok := x.GetEvent().(*Frame_O); ok {
		return x.O
	}
	return nil
}

func (x *Frame) GetI() []byte {
	if x, ok := x.GetEvent().(*Frame_I); ok {
		return x.I
	}
	return nil
}

func (x *Frame) GetR() uint32 {
	if x, ok := x.GetEvent().(*Frame_R); ok {
		return x.R
	}
	return 0
}

type isFrame_Event interface {
	isFrame_Event()
}

type Frame_O struct {
	O []byte `protobuf:"bytes,1,opt,name=o,proto3,oneof"`
}

type Frame_I struct {
	I []byte `protobuf:"bytes,2,opt,name=i,proto3,oneof"`
}

type Frame_R struct {
	R uint32 `protobuf:"varint,3,opt,name=r,proto3,oneof"`
}

func (*Frame_O) isFrame_Event() {}

func (*Frame_I) isFrame_Event() {}

func (*Frame_R) isFrame_Event() {}

var File_asciiproto_proto protoreflect.FileDescriptor

var file_asciiproto_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x73, 0x63, 0x69, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x40, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x01, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x01,
	0x6f, 0x12, 0x0e, 0x0a, 0x01, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x01,
	0x69, 0x12, 0x0e, 0x0a, 0x01, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x01,
	0x72, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b,
	0x61, 0x73, 0x63, 0x69, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_asciiproto_proto_rawDescOnce sync.Once
	file_asciiproto_proto_rawDescData = file_asciiproto_proto_rawDesc
)

func file_asciiproto_proto_rawDescGZIP() []byte {
	file_asciiproto_proto_rawDescOnce.Do(func() {
		file_asciiproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_asciiproto_proto_rawDescData)
	})
	return file_asciiproto_proto_rawDescData
}

var file_asciiproto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_asciiproto_proto_goTypes = []interface{}{
	(*Frame)(nil), // 0: main.Frame
}
var file_asciiproto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asciiproto_proto_init() }
func file_asciiproto_proto_init() {
	if File_asciiproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asciiproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_asciiproto_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Frame_O)(nil),
		(*Frame_I)(nil),
		(*Frame_R)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asciiproto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_asciiproto_proto_goTypes,
		DependencyIndexes: file_asciiproto_proto_depIdxs,
		MessageInfos:      file_asciiproto_proto_msgTypes,
	}.Build()
	File_asciiproto_proto = out.File
	file_asciiproto_proto_rawDesc = nil
	file_asciiproto_proto_goTypes = nil
	file_asciiproto_proto_depIdxs = nil
}
